### ISSUE TITLE
pre-caching player head textures

### ISSUE THREAD

**Issue by Martinnicchi** [SkyblockerMod/Skyblocker#1058]
### Describe the new feature.

I would be nice whenever game starts or hypixel api is updated to permanently cache player head textures (items from api), it might improve performance overall as well as in inventory when using JEI type mods.
Currently inventory becomes a bit laggy when opened without using "cache entry rendering", but when using it unloaded heads will have a default texture. It might also help with networking when minecraft won't be trying to download to cache textures for heads that we can easily download once, because they rarely change and we have whole list of them in hypixel api.

what to do:
    minecraft start: 
1. look for player_head ids in hypixel api
2. download all found 
3. tell minecraft to not redownload already downloaded textures
4. clear that cache on minecraft launch
    hypixel api update:
1. check hypixel api update date, when date not changed ignore
2. when date changed look for player_head ids in hypixel api
3. check for any texture changes in player_head textures files
4. download needed textures, cache them somewhere in minecraft directory
5. tell minecraft to not redownload already downloaded textures

Im not a programmer, you probably know this from reading what I've wrote above. apply this however you like it and if it is possible.
Instructions above might be inaccurate, I don't know shit, but yeah it would be cool if you implemented this.

**Comment by AzureAaron** [comment]
Player head textures are downloaded once by the client and cached forever so this wouldn't help unless it was your very first time playing the game; if you play frequently most player head textures are already cached (you can find this cache in the `assets/skins` folder in your Minecraft directory - this also means every single skin you've ever encountered is saved locally to your computer!). Render layers for player heads (what's used to render them internally) are also cached for the entire duration of the session so there is not much that can be done there, preemptively generating thousands of those for player heads that you might not even look at once in your session is a bit wasteful of memory.

The main reason why mods like REI, EMI, and JEI are laggy is because item rendering itself is inefficient and they render many items at once which exacerbates the problem; Mojang in this case needs to improve item rendering in order for it to be faster.
