### ISSUE TITLE
Parts of the quick navigation buttons may be located past the edges of the screen

### ISSUE THREAD

**Issue by Clozent** [SkyblockerMod/Skyblocker#152]
On my monitor (1080 by 1920), when I open the skyblock menu (or any other menu with a height of six), the quick navigation buttons move past the top/bottom edges of the screen as a result of the inventory popup expanding. A solution that could work would be to have a setting which will move the buttons to the sides of the inventory. There might be a better solution I haven't thought of, though.

**Comment by Julienraptor01** [comment]
I don't understand what you mean, could you show screenshots ?

**Comment by Clozent** [comment]
I forgot to mention I play on windowed mode, which narrows the screen vertically a bit.
Anyways, here is a screenshot:
![2023-05-17_14 44 09](https://github.com/SkyblockerMod/Skyblocker/assets/45975432/ab19211c-8aab-4708-87d6-94c0dbc5ffa8)

**Comment by Julienraptor01** [comment]
Oh i see, well, i know it won't really solve the real problem, but you can lower your UI size by using the max instead of auto (the difference between both is not huge but max should fit maybe) or not play on a small window and instead make it windowed fullscreen so that it has more screenspace whitout removing the problem of your OS taskbar and window titlebar not being there
On the fixing of this problem tho, making buttons be able to move or be on the side would maybe necessitate a rewrite of this part of the mod, because currently we're just using buttons similar the creative UI inventory (i'm not exactly sure to remember how it's done)

**Comment by kevinthegreat1** [comment]
I don't think there is an easy solution or is it worth solving. The current tab system is also consistent with the creative menu. I would suggest lowering the gui scale as a fix.
