### ISSUE TITLE
Themeless improvements list

### ISSUE THREAD

**Issue by x-yingcan-x** [SkyblockerMod/Skyblocker#321]
I may update this from time to time, because some features are not so important to open an issue.
ignoring this is fine, as many of and take a long time and only improve a little or unreasonable.
# Improvements
- [ ] Display a box where you will be teleported to.
- [ ] Highlighter for glowing mushroom
- [x] Highlighter for ender node
- [x] Display your baubles in inventory (I give up to show the pet at the same time)
- [x] Hide durability for pickno2000 if it has full durability.
- Stop highlight audience mobs (e.g. lost adventures) and bats in F4 boss fight.(highlight effect breaks fps)
this is less important since the vanilla highlight effect is replaced with a more effecient one.
- hide the buff info in dungeon when you pick up buff stones.(because they spam in your chat)
  can be done by Custom chat rules
- [x] Display scores beside dungeon map.
- [x] notice you if someone pick up wither key / blood key and highlight the door.
- [x] Water borad solver
- [x] Ice Path/Ice fill solver

### Images

positions of baubles and pet slot.
![baublesandpet](https://github.com/SkyblockerMod/Skyblocker/assets/99530733/12d99deb-2cd3-4da1-92ab-435d0a806fda)

**Comment by x-yingcan-x** [comment]
by the way, will the config lib change to Malilib or Yet another config lib?or neither?

**Comment by Julienraptor01** [comment]
Cheating is a straight no

**Comment by Julienraptor01** [comment]
> by the way, will the config lib change to Malilib or Yet another config lib?or neither?

YACL was cited, Malilib not
I don't think Malilib would fit our needs + Malilib doesn't use the vanilla keybinding which can be very annoying

**Comment by msg-programs** [comment]
> middle click to switch to Superboom TNT to boom the wall in dungeon.

Word of warning: This _might_ cause issues if you don't have the TNT in your hotbar. I accidentally played with Inventory Profiles Next enabled once and got kicked for something like "Invalid Client Inventory Move" because IPN tried to move things around. IIRC this happend every time I used the dungeon orb.

**Comment by Julienraptor01** [comment]
> ### Describe the new feature.
> 
> Sorry for my english , if you feel cofusing about sth , just ask me.
> # Improvements
> - prevent you from using Grappling Hook 2s after use.

This would need a special case for bat person armor + extremly niche

> - prevent you from place FoT.

Why ? 

> - prevent you from using quickNav for 5s after transfer to another server.

Why ? 

> - hide durability for pickno2000 if it has full durability.

This could maybe be done, it's a small change

> - hide dungeon buff information.

What / where ? 

> - hide prize information in accessory bag/fishing bag/quiver;armors you are wearing and in wardrobe;items in collection menu and so on.

Disable the feature if you don't want price information, it can be toggled in config

> - notice you if a event is coming.
> 	- for Jacob's Farming Contest,only notice you if it include certain crops you selected.

A notice for Jacob contest was already mentionned in a suggestion iirc

> - notice you if someone picked up wither key or blood key and highlight the door.

This could maybe be done

> - make items with no tooltip unclickable in menus.

Well idk about how preventing clicks would work, but cancelling them is not allowed per hypixel rules

> - warn you if you using wrong armor set/Baubles/pet/tools in garden/dungeon/dwarven mine\(as you set)

This could maybe be done

> - ability to reset custom name/armor trim/dye color.

Already available, just don't pass any name/trim name/color

> - middle click to switch to Superboom TNT to boom the wall in dungeon.

If you mean switching an item from your inventory into your hotbar, it's a cheat 
If you mean switching the hotbar slot, it could technically be done, but i mean it shouldn't be that hard to press the key linked to that slot to switch to it
And if it include automatically right clicking, after swapping, it's a cheat

> - left click in Sack of Sacks to open it.

How would you expect us to do that, transform right clicks into left ? Extremly niche + the right mouse button isn't that far is it ? 

> - hold left click to shoot at max speed as hold right click.

Just hold right click ? 

> - ice path solver.

This could maybe be done

> - display a box where you will be teleported to instead of highlight block.

Yes the behavior of TP overlay is wrong for everything else than Etherwarp and will be changed at some point in the future

> - make your position on dungeon map full-client-side

What would be the point ?

> - highlight glowing mushroom/glowing obsidian.

Maybe a glowing mushroom/ender node highlighter could be done

> - display your baubles \(and pet) on the left side of your inventory or right side of your player model.

This could maybe be done

> - show you the progress from certain source to level up your skill.e.g. My farming skill is L29,require 1.2m XP to level up,I get 5 farming XP by harvest wheat,so when I harvest wheat it will display x/240000 wheat \(to level up) .

This could maybe be done tho i don't really understand the purpose ? 
All you want is a widget for EXP progress ? 

> - preview the mana/health cost on bar.

Maybe this could be done

> ## may require caching
> - display dwarven commissions in exact number of items or mobs

This would be hard to make accurate for some things i think ? 

> - display items the guests in garden required above their head. and notice you to buy them when you open BZ menu.

Maybe this could be done, but you'll need to right click NPCs before it show the required things anyway, so you might as well just take the time and read ? 

> - notice you if you can go to rift for free.

This would basically be a time before free rift, it could maybe be done

> # Cheating
> - AutoPlay for Chronomatron/Ultrasequencer/Superpairs
> - True instant breaking - break blocks in a row instantly\(similar to Nuker in some way).

As i've said, everything here is against hypixel rules, so NO

> ### Images
> 
> positions of baubles and pet slot.
> ![baublesandpet](https://github.com/SkyblockerMod/Skyblocker/assets/99530733/12d99deb-2cd3-4da1-92ab-435d0a806fda)

**Comment by LifeIsAParadox** [comment]
> ### Describe the new feature.
> # Improvements
> 
>     [...]

Like Julienraptor wrote most of your suggestion couldn't be done. Because this would be cheating, and this mod is going by the [rule of Hypixel](https://support.hypixel.net/hc/en-us/articles/6472550754962-Hypixel-Allowed-Modifications). I am sorting your suggestion to doable not doable and not be allowed.

## Would be doable

- [ ] prevent you from using quickNav for 5s after transfer to another server as it simply shows "You may only use this command after 4s on the server!" and doesnt open the menu. # would be simpler to wait for hypixel tells you that it changed successfully the server
- [ ] hide durability for pickno2000 if it has full durability.
- [ ] hide the buff info in dungeon when you pick up buff stones , it's annoying and spam in your chat.
- [ ] (dump)notice you when a Jacob's Farming Contest comes with certain crops you selected.
- [ ] notice you if someone pick up wither key / blood key and highlight the door.
- [ ] warn you if you using wrong armor set/Baubles/pet/tools in garden/dungeon/dwarven mine(as you set) # maybe doable looks complicated
- [ ] ice path solver.
- [ ] display a box where you will be teleported to instead of highlight block.
- [ ] highlight glowing mushroom/ender node.
- [ ] display your baubles (and pet) on the left side of your inventory or right side of your player model.
- [ ] show you the progress from certain source to level up your skill.e.g. My farming skill is L29,require 1.2m XP to level up,I get 5 farming XP by harvest wheat,so when I harvest wheat it will display x/240000 wheat (to level up) .
- [ ] preview the mana/health cost on bar.

## Not Doable

I see the not doable stuff is already taken out of the feature request.

## Not Allowed

- prevent you from using Grappling Hook 2s after use. # blocking click not allowed
- make background items in menus can't pick up.it's annoying with high ping. # blocking click not allowed
- prevent you from take out sack in Sack of Sacks. # blocking click not allowed

**Comment by x-yingcan-x** [comment]
we need sth to put random ideas, and i think i should just close this
