### ISSUE TITLE
Wider range of version compatibility

### ISSUE THREAD

**Issue by Arozoid** [SkyblockerMod/Skyblocker#789]
### Describe the new feature.

Because CIT Resewn and OptiFine are probably going to take a while figuring out how to port NBT into components, I would like to suggest that the range of compatibility is at least extended to 1.20.4+, due to some of the people who recently tried to port to the newest release of Skyblocker (v1.21) being not able to bring along their Skyblock resource packs.

This actually annoyed one of my friends who were making the switch to Skyblocker, because of the superior QoL features having been added to the next version. Therefore, I want to suggest that the version compatibility range should be extended back to 1.20.4.

**Comment by FounderHawk** [comment]
I came here to post this myself.

For an unknown amount of time 1.20.4 will be the new standard version for mods, such as 1.8 and 1.12 were due to other breaking changed from MC. As it stands I'm stuck between choosing the latest features, and using no texture pack 🤮 or sticking to the lesser featured 1.20.4 version, to keep the texture packs.

**Comment by XcusanaIi** [comment]
I've seen a version rollback of "Skyblocker 1.21.1 for 1.20.6". Hopefully there will be a "Skyblocker 1.21.1 for 1.20.4"

**Comment by kevinthegreat1** [comment]
Unfortunately, we are not considering backporting to 1.20.4 or lower. The [1.20.5 changes](https://fabricmc.net/2024/04/19/1205.html) are extremely breaking and basically impossible to backport, especially with item components. The problem with resource packs is temporary anyways.
