### ISSUE TITLE
Skyblocker Config Failed to Load

### ISSUE THREAD

**Issue by SxOxUxP** [SkyblockerMod/Skyblocker#894]
### What happened?

In the mod menu it says "Failed to load config screen for 'skyblocker'"

### Screenshots

![Screenshot_1](https://github.com/user-attachments/assets/4aa2df12-1723-48fa-80e9-921302566a1d)

### Log output

[2024-08-04-7.log.gz](https://github.com/user-attachments/files/16489576/2024-08-04-7.log.gz)

### Minecraft Version

1.21.0

### Skyblocker Version

skyblocker-1.21.1+1.21.1.jar

### Additional context

Need this so I can do Fairy Souls easily, if there's a command to enable it without going to configs that would also fix my problem.

**Comment by Emirlol** [comment]
There were 2 new buttons added to the quicknav menu at some time, and afaik this happens when you switch versions back and forth or something like that. I can fix and send it back if you can share your main `skyblocker.json` config.

**Comment by Emirlol** [comment]
[skyblocker.json](https://github.com/user-attachments/files/16495683/skyblocker.json)
Removed the quicknav settings so that it can re-generate correct ones, this will cause your quicknav settings to reset but at least the whole config will work now.

No need to feel sorry, I'm also at fault here for the same reason. I could've told you the steps to fix it rather than doing it for you, you would've gotten the fixed version a lot earlier as a result of that.

**Comment by SxOxUxP** [comment]
Perfect it works now, thank you so much! :D
